//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказные_изделия
    {
        public string Артикул_изделия { get; set; }
        public string Номер_заказа { get; set; }
        public Nullable<short> Количество { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        public virtual Изделие Изделие { get; set; }
    }
}
