//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ()
        {
            this.Заказные_изделия = new HashSet<Заказные_изделия>();
        }
    
        public string Номер { get; set; }
        public System.DateTime Дата { get; set; }
        public string Этап_выполнения { get; set; }
        public string Заказчик { get; set; }
        public string Менеджер { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
    
        public virtual Пользователь Пользователь { get; set; }
        public virtual Пользователь Пользователь1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказные_изделия> Заказные_изделия { get; set; }
    }
}
