//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Склад_ткани
    {
        public string Рулон { get; set; }
        public string Артикул_ткани { get; set; }
        public double Ширина { get; set; }
        public double Длина { get; set; }
    
        public virtual Ткань Ткань { get; set; }
    }
}
