//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ткань
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ткань()
        {
            this.Склад_ткани = new HashSet<Склад_ткани>();
            this.Изделие = new HashSet<Изделие>();
        }
    
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public string Цвет { get; set; }
        public string Рисунок { get; set; }
        public byte[] Изобраажение { get; set; }
        public string Состав { get; set; }
        public double Ширина { get; set; }
        public Nullable<double> Длина { get; set; }
        public decimal Цена { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Склад_ткани> Склад_ткани { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Изделие> Изделие { get; set; }
    }
}
